# Generated by Django 5.1.1 on 2025-01-06 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogPop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='claps',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='loves',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
