# Generated by Django 5.1.1 on 2025-01-07 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogPop', '0004_alter_reaction_reaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='reaction_type',
            field=models.CharField(choices=[('like', 'Like'), ('love', 'Love'), ('clap', 'Clap')], max_length=10),
        ),
    ]
